
services:
  frontend:
    image: tseq-frontend-dev
    container_name: tseq-frontend-dev
    build:
      context: ./tsequencer-frontend
      dockerfile: Dev.Dockerfile
    develop:
      watch:
      - action: sync
        path: ./tsequencer-frontend
        target: ./usr/src/app
        ignore:
          - node_modules
  
  backend:
    image: tseq-backend-dev
    container_name: tseq-backend-dev
    build:
      context: ./tsequencer-backend
      dockerfile: Dev.Dockerfile
    volumes:
      - ./:/user/src/app/tsequencer-backend
    ports:
      - 5179:5179
    environment:
      - JWT_ISSUER=Issuer
      - JWT_AUDIENCE=Users
      - JWT_SECRET=thisisnotasecretbutyetthisisnowlongenough

  mongo:
    image: mongo
    container_name: mongodb_dev
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_user
      MONGO_INITDB_ROOT_PASSWORD: dev_password
      MONGO_INITDB_ROOT_DATABASE: dev_db
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - mongo

volumes:
  mongo_data: