@tsequencer_hostAddress = http://localhost:5179

# USER

GET {{tsequencer_hostAddress}}/api/user
Accept: application/json

###
GET {{tsequencer_hostAddress}}/api/user/663e07dd8d24b98b75527bb6
Accept: application/json

###
POST {{tsequencer_hostAddress}}/api/user
Content-Type: application/json

{
    "username": "dermotbg",
    "password": "password"
}
###
PUT {{tsequencer_hostAddress}}/api/user/663e07dd8d24b98b75527bb6
Content-Type: application/json

{
    "newUsername": "dermotbg-2",
    "password": "password"
}

###
DELETE {{tsequencer_hostAddress}}/api/user/663e07dd8d24b98b75527bb6

# LOGIN
###
POST {{tsequencer_hostAddress}}/api/login
Content-Type: application/json

{
    "username": "dermotbg",
    "password": "password"
}



# SEQUENCER
###
GET {{tsequencer_hostAddress}}/api/sequencer
Accept: application/json

###
GET {{tsequencer_hostAddress}}/api/sequencer/user/663e07dd8d24b98b75527bb6
Accept: application/json

###
POST {{tsequencer_hostAddress}}/api/sequencer
Content-Type: application/json

{
    "name": "NewSequence",
    "userId": "663e07dd8d24b98b75527bb6",
    "sequence": 
    [   
        {
            "instruments": ["kick","closedHH"],
            "metronomes": ["metroUp"],
            "extraCSS": "",
            "gain": { "kick": 3, "clap": 1, "closedHH": 0.4, "ride": 1 }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "clap",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 3,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 1,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "clap",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 3,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "clap",
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 2.1,
                "closedHH": 1,
                "ride": 1
            }
        }
    ]
}

###

DELETE {{tsequencer_hostAddress}}/api/sequencer/663f3315e77e295a3c6af339