@tsequencer_hostAddress = http://localhost:5179

# USER

GET {{tsequencer_hostAddress}}/api/user
Accept: application/json

###
GET {{tsequencer_hostAddress}}/api/user/663e07dd8d24b98b75527bb6
Accept: application/json

###
POST {{tsequencer_hostAddress}}/api/user
Content-Type: application/json

{
    "username": "testerino",
    "password": "password",
    "confPassword": "password"
}
### Password
PUT {{tsequencer_hostAddress}}/api/user/pw/666bf4dafc074a2c86e09844
Content-Type: application/json

{
    "username": "testerino",
    "password": "password",
    "newPassword": "wordpass"
}

### Username
PUT {{tsequencer_hostAddress}}/api/user/un/666bf4dafc074a2c86e09844
Content-Type: application/json

{
    "username": "testerino-2",
    "newUsername": "testerino",
    "password": "wordpass"
}

###
DELETE {{tsequencer_hostAddress}}/api/user/666bf218ad6271b8b353b1ac

# LOGIN
###
POST {{tsequencer_hostAddress}}/api/login
Content-Type: application/json

{
    "username": "dermotbg",
    "password": "password"
}



# SEQUENCER
###
GET {{tsequencer_hostAddress}}/api/sequencer
Accept: application/json

###
GET {{tsequencer_hostAddress}}/api/sequencer/user/663e07dd8d24b98b75527bb6
Accept: application/json

###
POST {{tsequencer_hostAddress}}/api/sequencer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2NjNlMDdkZDhkMjRiOThiNzU1MjdiYjYiLCJyb2xlIjoidXNlciIsIm5iZiI6MTcxNTUwOTc0MSwiZXhwIjoxNzE1NTExNTQxLCJpYXQiOjE3MTU1MDk3NDEsImlzcyI6IkFkbWluIiwiYXVkIjoiVXNlciJ9.1uMtGDLvcptsjiiGiiV1CoYbHdmbIJ9YM91CIuWKRpg

{
    "name": "NewSequence",
    "userId": "663e07dd8d24b98b75527bb6",
    "sequence": 
    [   
        {
            "instruments": ["kick","closedHH"],
            "metronomes": ["metroUp"],
            "extraCSS": "",
            "gain": { "kick": 3, "clap": 1, "closedHH": 0.4, "ride": 1 }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "clap",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 3,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 1,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "kick",
                "clap",
                "closedHH"
            ],
            "metronomes": [
                "metroDown"
            ],
            "extraCSS": "",
            "gain": {
                "kick": 3,
                "clap": 3,
                "closedHH": 0.4,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1,
                "ride": 1
            }
        },
        {
            "instruments": [
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 1,
                "closedHH": 1.9,
                "ride": 1
            }
        },
        {
            "instruments": [
                "clap",
                "closedHH"
            ],
            "metronomes": [],
            "extraCSS": "",
            "gain": {
                "kick": 1,
                "clap": 2.1,
                "closedHH": 1,
                "ride": 1
            }
        }
    ]
}

###

DELETE {{tsequencer_hostAddress}}/api/sequencer/663f3315e77e295a3c6af339