@tsequencer_hostAddress = http://localhost:5179

GET {{tsequencer_hostAddress}}/api/user
Accept: application/json

###
POST {{tsequencer_hostAddress}}/api/user
Content-Type: application/json

{
    "username": "dermotbg",
    "password": "password"
}
###
PUT {{tsequencer_hostAddress}}/api/user/663dffc6cc27a33dc3e51a30
Content-Type: application/json

{
    "newUsername": "dermotbg-2",
    "password": "password"
}

###
DELETE {{tsequencer_hostAddress}}/api/user/663dffc6cc27a33dc3e51a30